version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
    open-pull-requests-limit: 10
    reviewers:
      - "your-github-username"
    labels:
      - "dependencies"
      - "automated"
    groups:
      eslint:
        patterns:
          - "eslint*"
          - "@typescript-eslint/*"
      jest:
        patterns:
          - "jest*"
          - "ts-jest"
      types:
        patterns:
          - "@types/*"
    ignore:
      # Ignore major version updates for critical dependencies
      - dependency-name: "typescript"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@angular/*"
        update-types: ["version-update:semver-major"]
  
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "ci"
      - "automated"