#!/bin/bash
# Auto-generated Angular Migration Script
# Generated by ng-migration-analyzer
# Migration: Angular 17 → 18

set -e

echo "=== Angular Migration Script ==="
echo "Migration: Angular 17 → 18"
echo ""

# ⚠️  ERROR: Incompatible packages detected!
# The following packages are incompatible with Angular 17 and must be resolved:
# - @angular/flex-layout (^15.0.0-beta.42) - Only supports Angular up to version 15
#   Alternative: @angular/cdk/layout

echo "❌ ERROR: Incompatible packages detected!"
echo ""
echo "The following packages must be removed or replaced before migration:"
echo "  - @angular/flex-layout: Only supports Angular up to version 15"
echo "    → Suggested alternative: @angular/cdk/layout"
echo ""
echo "Please resolve these incompatible packages before running the migration."
exit 1
