#!/bin/bash
# Auto-generated Angular Migration Script
# Generated by ng-migration-analyzer
# Migration: Angular 17 → 18

set -e

echo "=== Angular Migration Script ==="
echo "Migration: Angular 17 → 18"
echo ""

# ⚠️  WARNING: Incompatible packages detected!
# The following packages are incompatible with Angular 17: @angular/flex-layout
# You must resolve these issues before running this script:
# - Replace @angular/flex-layout with @angular/cdk/layout (see migration guide: https://github.com/angular/flex-layout/wiki/Using-Angular-CDK-Layout)

echo "⚠️  Please resolve the incompatible packages listed above before proceeding!"
echo "Press Ctrl+C to cancel, or Enter to continue anyway..."
read -p ""

# Step 1: Pre-migration dependency fixes
echo "Fixing dependencies before migration..."
npm install zone.js@~0.14.0 --save

echo "Cleaning and reinstalling..."
rm -rf node_modules package-lock.json
npm install

# Step 2: Update Angular CLI
echo "Updating Angular CLI..."
npm install -g @angular/cli@18

# Step 3: Run Angular migration
echo "Running Angular migration..."
ng update @angular/core@18 @angular/cli@18 --allow-dirty

# Step 4: Update additional Angular packages
echo "Updating additional Angular packages..."
ANGULAR_PACKAGES=$(grep -o '"@angular/[^"]*"' package.json | grep -v '@angular/core\|@angular/cli' | cut -d'"' -f2 | sort -u)
for pkg in $ANGULAR_PACKAGES; do
    echo "Updating $pkg..."
    ng update ${pkg}@18 --allow-dirty || true
done

# Step 5: Clean install
echo "Running clean install..."
rm -rf node_modules package-lock.json
npm install

# Step 6: Build project
echo "Building project..."
npm run build

echo ""
echo "=== Migration Complete ==="
echo "Review the changes and test your application"
echo "See .ngma/suggestions.md for additional manual fixes"
